services:
    Mstudio\ContaoSimpleCart\Service\CartService:
        autowire: true
        autoconfigure: true
        public: true

    Mstudio\ContaoSimpleCart\Controller\FrontendModule\ShoppingCartController:
        autowire: true
        autoconfigure: true
        public: true

    Mstudio\ContaoSimpleCart\Controller\FrontendModule\CheckoutController:
        autowire: true
        autoconfigure: true
        public: true
